
*creates locals to create cancersite variable for graph labels
*separate locals fullname (name + ICD code), name only or ICD10 code only

*full  name plus icd
		if "`site'"=="bla" local nameicd "Bladder (C67)"
		if "`site'"=="cns" local nameicd "Brain/CNS (C71-72)"
		if "`site'"=="col" local nameicd "Colorectal (C18-C20)"
		if "`site'"=="gas" local nameicd "Stomach (C16)"
		if "`site'"=="kid" local nameicd "Kidney (C64)"
		if "`site'"=="leu" local nameicd "Leukemia (C91-95)"
		if "`site'"=="liv" local nameicd "Liver (C22)"
		if "`site'"=="lun" local nameicd "Lung (C34)"
		if "`site'"=="mel" local nameicd "Malignant melanoma (C43)"
		if "`site'"=="mye" local nameicd "Multiple myeloma (C90)"
		if "`site'"=="nhl" local nameicd "Non-Hodgkin lymphoma (C82-85)"
		if "`site'"=="oes" local nameicd "Oesophageal (C15)"
		if "`site'"=="ora" local nameicd "Oral Cavity (C00-06)"
		if "`site'"=="pan" local nameicd "Pancreas (C25)"
		if "`site'"=="pro" local nameicd "Prostate (C61)"
		if "`site'"=="thy" local nameicd "Thyroid (C73)"
		if "`site'"=="bre" local nameicd "Breast (C50)"
		if "`site'"=="cer" local nameicd "Cervix (C53)"
		if "`site'"=="ova" local nameicd "Ovaries (C56)"
		if "`site'"=="ute" local nameicd "Uterus (C54-55)"
		
*full name
		if "`site'"=="bla" local fullname "Bladder"
		if "`site'"=="cns" local fullname "Brain/CNS"
		if "`site'"=="col" local fullname "Colorectal"
		if "`site'"=="gas" local fullname "Stomach"
		if "`site'"=="kid" local fullname "Kidney"
		if "`site'"=="leu" local fullname "Leukemia"
		if "`site'"=="liv" local fullname "Liver"
		if "`site'"=="lun" local fullname "Lung"
		if "`site'"=="mel" local fullname "Malignant melanoma"
		if "`site'"=="mye" local fullname "Multiple myeloma"
		if "`site'"=="nhl" local fullname "Non-Hodgkin lymphoma"
		if "`site'"=="oes" local fullname "Oesophageal"
		if "`site'"=="ora" local fullname "Oral Cavity"
		if "`site'"=="pan" local fullname "Pancreas"
		if "`site'"=="pro" local fullname "Prostate"
		if "`site'"=="thy" local fullname "Thyroid"
		if "`site'"=="bre" local fullname "Breast"
		if "`site'"=="cer" local fullname "Cervix"
		if "`site'"=="ova" local fullname "Ovaries"
		if "`site'"=="ute" local fullname "Uterus"

*name (to combine with ICD on second line)
		if "`site'"=="bla" local name "Bladder"
		if "`site'"=="cns" local name "Brain/CNS"
		if "`site'"=="col" local name "Colorectal"
		if "`site'"=="gas" local name "Stomach"
		if "`site'"=="kid" local name "Kidney"
		if "`site'"=="leu" local name "Leukemia"
		if "`site'"=="liv" local name "Liver"
		if "`site'"=="lun" local name "Lung"
		if "`site'"=="mel" local name "Malignant"
		if "`site'"=="mye" local name "Multiple"
		if "`site'"=="nhl" local name "Non-Hodgkin"
		if "`site'"=="oes" local name "Oesophageal"
		if "`site'"=="ora" local name "Oral Cavity"
		if "`site'"=="pan" local name "Pancreas"
		if "`site'"=="pro" local name "Prostate"
		if "`site'"=="thy" local name "Thyroid"
		if "`site'"=="bre" local name "Breast"
		if "`site'"=="cer" local name "Cervix"
		if "`site'"=="ova" local name "Ovaries"
		if "`site'"=="ute" local name "Uterus"

*icd
		if "`site'"=="bla" local icd "(C67)"
		if "`site'"=="cns" local icd "(C71-72)"
		if "`site'"=="col" local icd "(C18-C20)"
		if "`site'"=="gas" local icd "(C16)"
		if "`site'"=="kid" local icd "(C64)"
		if "`site'"=="leu" local icd "(C91-95)"
		if "`site'"=="liv" local icd "(C22)"
		if "`site'"=="lun" local icd "(C34)"
		if "`site'"=="mel" local icd "melanoma(C43)"
		if "`site'"=="mye" local icd "myeloma(C90)"
		if "`site'"=="nhl" local icd "lymphoma(C82-85)"
		if "`site'"=="oes" local icd "(C15)"
		if "`site'"=="ora" local icd "(C00-06)"
		if "`site'"=="pan" local icd "(C25)"
		if "`site'"=="pro" local icd "(C61)"
		if "`site'"=="thy" local icd "(C73)"
		if "`site'"=="bre" local icd "(C50)"
		if "`site'"=="cer" local icd "(C53)"
		if "`site'"=="ova" local icd "(C56)"
		if "`site'"=="ute" local icd "(C54-55)"


